ktor:
    deployment:
        port: 8080
    development: true
    application:
        modules:
            - com.example.ApplicationKt.module

storage:
    user: "postgres"
    password: "4fFzG5313GCQnLCr"
    jdbcURL: URL=jdbc:postgresql://localhost:5432/postgres
